-- Neurovex Full Supabase Database Schema
-- Run this entire script in the Supabase SQL Editor

-------------------------------------------------------------
-- 1. BASE TABLES
-------------------------------------------------------------

-- Profiles (Matches Supabase Auth)
CREATE TABLE public.profiles (
    id UUID REFERENCES auth.users(id) ON DELETE CASCADE PRIMARY KEY,
    full_name TEXT,
    role TEXT DEFAULT 'User',
    purpose TEXT DEFAULT 'Research',
    email TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Sessions (Hardware Recording Sessions)
CREATE TABLE public.sessions (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    start_time TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    end_time TIMESTAMP WITH TIME ZONE,
    avg_focus FLOAT DEFAULT 0.0,
    max_focus FLOAT DEFAULT 0.0,
    csv_url TEXT,
    device_connected BOOLEAN DEFAULT TRUE
);

-- EEG Data (High-frequency brainwave data)
CREATE TABLE public.eeg_data (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    timestamp BIGINT NOT NULL,
    raw_value INT NOT NULL,
    focus_level FLOAT NOT NULL
);

-- Hardware Logs (Control Commands sent to ESP32 L298N)
CREATE TABLE public.hardware_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    session_id UUID REFERENCES public.sessions(id) ON DELETE CASCADE,
    command TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Game Scores (For the Brain Games Module)
CREATE TABLE public.game_scores (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) ON DELETE CASCADE,
    game_type VARCHAR(50) NOT NULL,
    score NUMERIC NOT NULL,
    metrics JSONB DEFAULT '{}'::jsonb,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);


-------------------------------------------------------------
-- 2. INDEXES (For Performance)
-------------------------------------------------------------
CREATE INDEX idx_sessions_user ON public.sessions(user_id);
CREATE INDEX idx_eeg_session ON public.eeg_data(session_id);
CREATE INDEX idx_hardware_session ON public.hardware_logs(session_id);
CREATE INDEX idx_game_scores_type_score ON public.game_scores(game_type, score DESC);
CREATE INDEX idx_game_scores_user ON public.game_scores(user_id);


-------------------------------------------------------------
-- 3. STORAGE BUCKETS (For CSV Exports)
-------------------------------------------------------------
-- Note: Requires Supabase Storage API. If inserting via SQL:
INSERT INTO storage.buckets (id, name, public) 
VALUES ('eeg-sessions', 'eeg-sessions', true)
ON CONFLICT (id) DO NOTHING;


-------------------------------------------------------------
-- 4. ROW LEVEL SECURITY (RLS) POLICIES
-------------------------------------------------------------
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.eeg_data ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.hardware_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.game_scores ENABLE ROW LEVEL SECURITY;

-- Profile Policies
CREATE POLICY "Users can view own profile" 
ON public.profiles FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Users can update own profile" 
ON public.profiles FOR UPDATE USING (auth.uid() = id);

-- Session Policies
CREATE POLICY "Users can view own sessions" 
ON public.sessions FOR SELECT USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own sessions" 
ON public.sessions FOR INSERT WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own sessions" 
ON public.sessions FOR UPDATE USING (auth.uid() = user_id);

-- EEG Data Policies
CREATE POLICY "Users can view own EEG data" 
ON public.eeg_data FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.sessions WHERE sessions.id = eeg_data.session_id AND sessions.user_id = auth.uid())
);

CREATE POLICY "Users can insert own EEG data" 
ON public.eeg_data FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.sessions WHERE sessions.id = eeg_data.session_id AND sessions.user_id = auth.uid())
);

-- Hardware Log Policies
CREATE POLICY "Users can view own hardware logs" 
ON public.hardware_logs FOR SELECT USING (
    EXISTS (SELECT 1 FROM public.sessions WHERE sessions.id = hardware_logs.session_id AND sessions.user_id = auth.uid())
);

CREATE POLICY "Users can insert own hardware logs" 
ON public.hardware_logs FOR INSERT WITH CHECK (
    EXISTS (SELECT 1 FROM public.sessions WHERE sessions.id = hardware_logs.session_id AND sessions.user_id = auth.uid())
);

-- Game Score Policies
CREATE POLICY "Scores are publicly readable" 
ON public.game_scores FOR SELECT TO authenticated, anon USING (true);

CREATE POLICY "Users can insert own scores" 
ON public.game_scores FOR INSERT WITH CHECK (auth.uid() = user_id);


-------------------------------------------------------------
-- 5. AUTHENTICATION TRIGGERS
-------------------------------------------------------------
-- Automatically create a Profile when a User signs up
CREATE OR REPLACE FUNCTION public.handle_new_user() 
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.profiles (id, full_name, email)
  VALUES (new.id, new.raw_user_meta_data->>'full_name', new.email);
  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function on auth.users insert
DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();
